### ISSUE TITLE
Export Extension stopped working after 2.2.0 update

### ISSUE THREAD

**Issue by haniunc** [TheInformationLab/Tableau-Extension-ExportAll#58]
Hi Craig,

I just saw that an update has been made. I checked my dashboards and the export buttons no longer work on the server. I also opened them in the desktop version, and they stopped working when i reloaded them. Is there something we need to do on our end to get the update to work?

Thanks

**Comment by craigbloodworth** [comment]
Hi,

Can you please post a screenshot? Ideally also any errors that show in the browser console (in Chrome right click -> Inspect)

Cheers,

Craig

**Comment by haniunc** [comment]
![screenshot1](https://user-images.githubusercontent.com/53050839/91327909-2b8c1c00-e794-11ea-9fd9-326d73608a82.jpg)
![screenshot2](https://user-images.githubusercontent.com/53050839/91327922-2dee7600-e794-11ea-8848-49f6da0abde1.jpg)

In screenshot 2, usually there is a button there, but now it's just blank and i try to select with a mouse to see, but there is no object or anything. Also, I tried deleting it and adding it again in the desktop version, but it added a blank box and does not allow me to configure.

I am using Tableau 2020.1.0

Thanks for looking into this!

**Comment by craigbloodworth** [comment]
Thanks. Can you please switch to the console tab instead of the 'Elements' tab and send that screenshot with as many of the errors as possible on display?

**Comment by haniunc** [comment]
![screenshot3](https://user-images.githubusercontent.com/53050839/91328785-5a56c200-e795-11ea-9da0-dda2882d4f1b.jpg)
Is this what you need?

**Comment by haniunc** [comment]
![screenshot4](https://user-images.githubusercontent.com/53050839/91330500-85421580-e797-11ea-8b10-c196412ffbc4.jpg)
I also uploaded an empty dashboard with just the extension and above is the screenshot for the errors

**Comment by craigbloodworth** [comment]
Thanks. I'll get back to you

**Comment by marielpandaan** [comment]
Hi @craigbloodworth ,

The extension also stopped working for me today, both in the server and desktop version.

![image](https://user-images.githubusercontent.com/70288785/91344655-ccb8b800-e810-11ea-9748-3846bfcc6a15.png)

Thanks for checking.

**Comment by craigbloodworth** [comment]
@marielpandaan which version of Tableau are you using?

**Comment by craigbloodworth** [comment]
I'm mobile at the moment so unable to verify but I believe this is a simple URL addressing issue. Will hopefully have a fix in a couple of hours

**Comment by marielpandaan** [comment]
> @marielpandaan which version of Tableau are you using?
2019.3.4

**Comment by craigbloodworth** [comment]
Go ahead and test it again, I've just pushed a fix that should work @haniunc @marielpandaan

**Comment by jessicalois** [comment]
@craigbloodworth, I work with @haniunc and just tested - the button now appears but as soon as the button loads, the dashboard refreshes itself. This happens over and over , each time the button loads again, the dashboard refreshes again, ad infinitum.

**Comment by haniunc** [comment]
![screenshot5](https://user-images.githubusercontent.com/53050839/91349726-b3355300-e7b3-11ea-8dbb-47d492d5e01f.JPG)
Hi Craig,
Here are the new errors that are popping up now (and it keeps reloading and giving more errors)

**Comment by marielpandaan** [comment]
> Go ahead and test it again, I've just pushed a fix that should work @haniunc @marielpandaan

@craigbloodworth Working as expected for me now. Many thanks for the quick resolution!

**Comment by LyleEllerbach** [comment]
We are still having the refresh issues and the colors are still blue...

**Comment by craigbloodworth** [comment]
@LyleEllerbach the colour changed to blue as Tableau modified their official React UI framework which changed the primary style from green to blue and so the extension is now in keeping with the rest of the updated Tableau UI.

As for the refresh issue could you please confirm the version of Tableau you're running as well as a screenshot of your browser console so I can try & diagnose the issue

**Comment by craigbloodworth** [comment]
Closing this issue as the initial problem has been resolved
